"""add sending_party to settlement

Revision ID: 02d0bad29034
Revises: f5c36e392820
Create Date: 2025-05-25 13:19:54.274846

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '02d0bad29034'
down_revision = 'f5c36e392820'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settlement', sa.Column('sending_party_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'settlement', 'user', ['sending_party_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'settlement', type_='foreignkey')
    op.drop_column('settlement', 'sending_party_id')
    # ### end Alembic commands ###
