"""Add timestamps to disbursement

Revision ID: 15f10db21cd9
Revises: fa9e4238d483
Create Date: 2025-05-24 06:44:42.397017

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision = "15f10db21cd9"
down_revision = "fa9e4238d483"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "disbursement",
        sa.Column(
            "created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
    )
    op.add_column(
        "disbursement",
        sa.Column(
            "updated_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("disbursement", "updated_at")
    op.drop_column("disbursement", "created_at")
    # ### end Alembic commands ###
