"""add deleted_at to disbursement

Revision ID: 28807f4590cb
Revises: 9042993352c9
Create Date: 2025-05-24 19:41:09.985041

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision = "28807f4590cb"
down_revision = "9042993352c9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "disbursement", sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("disbursement", "deleted_at")
    # ### end Alembic commands ###
