"""add clerk_user_id to user

Revision ID: 2e60a74b06e2
Revises: c46415af1f57
Create Date: 2025-05-26 12:46:38.308505

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision = "2e60a74b06e2"
down_revision = "c46415af1f57"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column("clerk_user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.create_index(
        op.f("ix_user_clerk_user_id"), "user", ["clerk_user_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_clerk_user_id"), table_name="user")
    op.drop_column("user", "clerk_user_id")
    # ### end Alembic commands ###
