"""alter payer an on behalf of user on disbursement to foreign keys

Revision ID: 89a8c0e207aa
Revises: 2e60a74b06e2
Create Date: 2025-05-26 22:19:10.672416

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '89a8c0e207aa'
down_revision = '2e60a74b06e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('disbursement', sa.Column('paying_party_id', sa.Uuid(), nullable=False))
    op.add_column('disbursement', sa.Column('on_behalf_of_party_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(op.f('fk_disbursement_on_behalf_of_party_id_user'), 'disbursement', 'user', ['on_behalf_of_party_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_disbursement_paying_party_id_user'), 'disbursement', 'user', ['paying_party_id'], ['id'], ondelete='CASCADE')
    op.drop_column('disbursement', 'payer_id')
    op.drop_column('disbursement', 'paid_for_user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('disbursement', sa.Column('paid_for_user_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('disbursement', sa.Column('payer_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_disbursement_paying_party_id_user'), 'disbursement', type_='foreignkey')
    op.drop_constraint(op.f('fk_disbursement_on_behalf_of_party_id_user'), 'disbursement', type_='foreignkey')
    op.drop_column('disbursement', 'on_behalf_of_party_id')
    op.drop_column('disbursement', 'paying_party_id')
    # ### end Alembic commands ###
