"""add receiving_party to settlement

Revision ID: 90eb44cd0d21
Revises: 02d0bad29034
Create Date: 2025-05-25 13:22:25.654977

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '90eb44cd0d21'
down_revision = '02d0bad29034'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settlement', sa.Column('receiving_party_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'settlement', 'user', ['receiving_party_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'settlement', type_='foreignkey')
    op.drop_column('settlement', 'receiving_party_id')
    # ### end Alembic commands ###
