"""add settlement_id to disbursement

Revision ID: 966c11128694
Revises: 90eb44cd0d21
Create Date: 2025-05-25 14:24:10.775895

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision = "966c11128694"
down_revision = "90eb44cd0d21"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("disbursement", sa.Column("settlement_id", sa.Uuid(), nullable=True))
    op.create_foreign_key(
        op.f("fk_disbursement_settlement_id_settlement"),
        "disbursement",
        "settlement",
        ["settlement_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_disbursement_settlement_id_settlement"),
        "disbursement",
        type_="foreignkey",
    )
    op.drop_column("disbursement", "settlement_id")
    # ### end Alembic commands ###
