"""add owner_id to disbursement

Revision ID: c46415af1f57
Revises: 4eb225925f13
Create Date: 2025-05-25 20:39:30.097794

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision = "c46415af1f57"
down_revision = "4eb225925f13"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("disbursement", sa.Column("owner_id", sa.Uuid(), nullable=False))
    op.create_foreign_key(
        op.f("fk_disbursement_owner_id_user"),
        "disbursement",
        "user",
        ["owner_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_disbursement_owner_id_user"), "disbursement", type_="foreignkey"
    )
    op.drop_column("disbursement", "owner_id")
    # ### end Alembic commands ###
