"""Add table disbursement

Revision ID: f1b81aea6089
Revises: 1a31ce608336
Create Date: 2025-05-23 20:42:15.563831

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision = "f1b81aea6089"
down_revision = "1a31ce608336"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "disbursement",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("payer_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "paid_for_user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("currency", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("comment", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("disbursement")
    # ### end Alembic commands ###
