"""add owner to settlement

Revision ID: f5c36e392820
Revises: febd4b2e8f09
Create Date: 2025-05-25 13:16:27.102569

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f5c36e392820'
down_revision = 'febd4b2e8f09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settlement', sa.Column('owner_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'settlement', 'user', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'settlement', type_='foreignkey')
    op.drop_column('settlement', 'owner_id')
    # ### end Alembic commands ###
